const severityColors = {
  No: 'bg-emerald-100 text-emerald-700',
  Mild: 'bg-amber-100 text-amber-700',
  Moderate: 'bg-orange-100 text-orange-700',
  Severe: 'bg-rose-100 text-rose-700',
  Proliferative: 'bg-red-100 text-red-700',
};

export default function ClassificationResult({ result }) {
  if (!result) {
    return null;
  }

  const severityClass = severityColors[result.severity?.split(' ')[0]] || 'bg-slate-100 text-slate-700';

  return (
    <div className="medical-card p-6 sm:p-7">
      <div className="flex items-center justify-between gap-4">
        <div>
          <p className="section-label">DR Classification</p>
          <h2 className="mt-2 text-2xl font-semibold text-slate-900">{result.title}</h2>
        </div>
        <span className={`rounded-full px-3 py-1 text-xs font-semibold ${severityClass}`}>
          {result.severity || 'Moderate'}
        </span>
      </div>

      <div className="mt-6 rounded-2xl bg-sky-50 p-4 ring-1 ring-sky-100">
        <p className="text-sm text-slate-500">Confidence</p>
        <div className="mt-2 flex items-end justify-between gap-4">
          <span className="text-3xl font-semibold text-slate-900">{result.confidence?.toFixed(1) || '92.4'}%</span>
          <span className="rounded-full bg-sky-100 px-2 py-1 text-xs font-medium text-sky-700">
            {result.label || 'Moderate NPDR'}
          </span>
        </div>
        <div className="mt-4 h-2.5 overflow-hidden rounded-full bg-sky-200">
          <div
            className="h-full rounded-full bg-gradient-to-r from-sky-500 to-cyan-600"
            style={{ width: `${Math.min(Number(result.confidence || 92.4), 100)}%` }}
          />
        </div>
      </div>

      <div className="mt-6">
        <p className="text-sm font-medium text-slate-600">Severity level</p>
        <div className="mt-3 flex flex-wrap gap-2">
          {['No DR', 'Mild', 'Moderate', 'Severe', 'Proliferative DR'].map((level) => (
            <span
              key={level}
              className={`rounded-full px-3 py-1.5 text-xs font-medium ${
                level === result.severity
                  ? severityColors[level.includes('No') ? 'No' : level.split(' ')[0]] || 'bg-sky-100 text-sky-700'
                  : 'bg-slate-100 text-slate-600'
              }`}
            >
              {level}
            </span>
          ))}
        </div>
      </div>

      <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800">
        {result.disclaimer ||
          'This result is generated by an AI model for research/educational purposes and should not be considered a medical diagnosis.'}
      </div>
    </div>
  );
}
