export const VITE_API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';
export async function classifyImage(file) {
  const formData = new FormData();
  formData.append('image', file);

  const response = await fetch(`${VITE_API_BASE_URL}/api/classify/`, {
    method: 'POST',
    body: formData,
  });
  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error || 'Unable to classify this image.');
  }

  return data;
}

function resolveMediaUrl(path) {
  return new URL(path, `${VITE_API_BASE_URL}/`).toString();
}

export async function generateGradCAM(file) {
  const formData = new FormData();
  formData.append('image', file);

  const response = await fetch(`${VITE_API_BASE_URL}/api/gradcam/`, {
    method: 'POST',
    body: formData,
  });
  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error || 'Unable to generate the Grad-CAM visualization.');
  }

  return {
    ...data,
    results: Object.fromEntries(
      Object.entries(data.results || {}).map(([key, path]) => [key, resolveMediaUrl(path)]),
    ),
  };
}

export async function detectLesions(file) {
  const formData = new FormData();
  formData.append('image', file);

  const response = await fetch(`${VITE_API_BASE_URL}/api/lesions/`, {
    method: 'POST',
    body: formData,
  });
  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error || 'Unable to detect retinal lesions.');
  }

  return {
    ...data,
    result: {
      ...data.result,
      original_url: resolveMediaUrl(data.result.original_url),
      image_url: resolveMediaUrl(data.result.image_url),
      download_url: resolveMediaUrl(data.result.download_url),
    },
  };
}

const mockDelay = (callback, delay = 450) =>
  new Promise((resolve, reject) => {
    setTimeout(() => {
      try {
        resolve(callback());
      } catch (error) {
        reject(error);
      }
    }, delay);
  });

export async function uploadImage(file) {
  return mockDelay(() => ({
    id: Date.now(),
    name: file.name,
    size: file.size,
    type: file.type,
    previewUrl: URL.createObjectURL(file),
    uploadedAt: new Date().toISOString(),
  }));
}

export async function getClassification() {
  return mockDelay(() => ({
    title: 'Moderate Non-Proliferative Diabetic Retinopathy',
    confidence: 92.4,
    severity: 'Moderate',
    label: 'Moderate NPDR',
    disclaimer:
      'This result is generated by an AI model for research/educational purposes and should not be considered a medical diagnosis.',
  }));
}

export async function getLesionDetection() {
  return mockDelay(() => ({
    microaneurysms: 12,
    haemorrhages: 4,
    hardExudates: 18,
    softExudates: 2,
    summary:
      'Retinal findings suggest a moderate distribution of microaneurysms and hard exudates with localized haemorrhage.',
  }));
}

export async function getGradCAM() {
  return mockDelay(() => ({
    panels: [
      {
        key: 'input',
        title: 'Input Fundus',
        description: 'Original retinal fundus image provided for analysis.',
        image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=900&q=80',
      },
      {
        key: 'gradcam',
        title: 'True Grad-CAM',
        description: 'Highlights image regions that contributed to the selected model prediction.',
        image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=900&q=80',
      },
      {
        key: 'attention',
        title: 'Retinal Attention Map',
        description: 'Visual representation of regions emphasized by the retinal image processing pipeline.',
        image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=900&q=80',
      },
      {
        key: 'feature',
        title: 'YOLO26 Feature Visualization',
        description: 'Visualization of internal model feature representations.',
        image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=900&q=80',
      },
    ],
  }));
}

export async function downloadReport() {
  return mockDelay(() => ({
    fileName: 'retinal-analysis-report.txt',
    content: `Retinal Analysis Report\n\nAI-generated results are intended for research and educational purposes only and should not be used as a substitute for professional medical diagnosis.\n\nClassification: Moderate Non-Proliferative Diabetic Retinopathy (92.4% confidence)\nLesions: microaneurysms 12, haemorrhages 4, hard exudates 18, soft exudates 2\n`,
  }));
}
