from pathlib import Path
from threading import RLock

import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model


MODEL_PATH = Path(__file__).resolve().parent.parent / 'model' / 'best_aptos_cnn.keras'
ALLOWED_EXTENSIONS = {'jpg', 'jpeg', 'png', 'webp'}
CLASS_NAMES = [
    'No diabetic retinopathy',
    'Mild diabetic retinopathy',
    'Moderate diabetic retinopathy',
    'Severe diabetic retinopathy',
    'Proliferative diabetic retinopathy',
]
CLASS_SHORT_NAMES = ['No DR', 'Mild', 'Moderate', 'Severe', 'Proliferative DR']
CLASS_DESCRIPTIONS = [
    'No visible signs of diabetic retinopathy.',
    'Early changes that should be monitored regularly.',
    'Noticeable retinal changes that need clinical follow-up.',
    'Advanced changes requiring prompt specialist review.',
    'The most advanced stage; urgent specialist assessment is recommended.',
]
MODEL_LOCK = RLock()
MODEL = None


def get_model():
    global MODEL
    if MODEL is None:
        with MODEL_LOCK:
            if MODEL is None:
                MODEL = load_model(MODEL_PATH)
    return MODEL


def classify_image(uploaded_file):
    with Image.open(uploaded_file) as image:
        image_array = np.asarray(image.convert('RGB').resize((224, 224)), dtype=np.float32) / 255.0

    with MODEL_LOCK:
        probabilities = get_model().predict(np.expand_dims(image_array, axis=0), verbose=0)[0]

    probabilities = np.asarray(probabilities, dtype=np.float64)
    total = probabilities.sum()
    if total <= 0 or len(probabilities) != len(CLASS_NAMES):
        raise ValueError('The model returned an invalid prediction.')
    probabilities /= total
    predicted_index = int(np.argmax(probabilities))

    scores = [
        {
            'name': CLASS_NAMES[index],
            'short_name': CLASS_SHORT_NAMES[index],
            'value': float(probabilities[index]),
            'percent': round(float(probabilities[index]) * 100, 1),
        }
        for index in range(len(CLASS_NAMES))
    ]
    return {
        'title': CLASS_NAMES[predicted_index],
        'label': CLASS_SHORT_NAMES[predicted_index],
        'severity': CLASS_SHORT_NAMES[predicted_index],
        'description': CLASS_DESCRIPTIONS[predicted_index],
        'confidence': round(float(probabilities[predicted_index]) * 100, 1),
        'scores': scores,
        'disclaimer': 'This result is generated by an AI model for research/educational purposes and should not be considered a medical diagnosis.',
    }